
version: "3"
services:

   db:
     image: postgres:9.6
     restart: always
     environment:
       POSTGRES_PASSWORD: startinfo
       POSTGRES_DB: startinfo
     ports:
       - 5438:5432
     volumes:
       - ./postgres-data:/bitnami/postgresql/data
